### ISSUE TITLE
Plans for Python 3?

### ISSUE THREAD

**Issue by jcea** [pypxe/PyPXE#171]
Python 2.7 is deprecated and official support will be over in a few months. Is there any plan to support Python 3?

**Comment by icb-** [comment]
Yes, Python 3 support is next on my list of things to do.

**Comment by icb-** [comment]
I'm sure there are still a lot of incompatibilities, but the `python3` branch doesn't immediately raise an exception when run, for DHCP, TFTP, and HTTP servers, and is able to minimally serve their respective functions. My personal test environment is rather minimal, so I would appreciate if others are able to test as well.

**Comment by stappersg** [comment]
> the `python3` branch ... is able to minimally serve their respective functions.

I do read that as
> PyPXE works with Python 3 for the project lead

And think:  Just make the switch over

**Comment by icb-** [comment]
Sorry, I've been busy. Merged the Python 3 branch in 2e77904637a25d3f644724532b17c1243a4089a4 and removed the restriction in `setup.py`.

**Comment by jcea** [comment]
Please, publish in pypi I just installed "1.7.3", last release in pypi and it says:

```
Sorry, PyPXE doesn't support Python 3.
```

**Comment by icb-** [comment]
Thanks for the reminder. I've tagged and pushed v1.8.0 to [PyPi](https://pypi.org/project/PyPXE/1.8.0/)
