### ISSUE TITLE
Only DHCPACK when address is '0.0.0.0'?

### ISSUE THREAD

**Issue by rbclark** [pypxe/PyPXE#172]
In [dhcp.py](https://github.com/pypxe/PyPXE/blob/master/pypxe/dhcp.py#L369) the server will only respond when the DHCP Request is coming from address `0.0.0.0`. I'm not very familiar with DHCP and was wondering why the server only responds to requests coming from this address.

For example, if the DHCP client has a router between the server, the `address[0]` gets rewritten and looks like it comes from the router. In this case the DHCP server will not send DHCPACK. Is this server implemented without consideration for that case?

Thanks.

**Comment by icb-** [comment]
PyPXE implements a minimal DHCP server to make PXE booting work. It doesn't implement [RFC3046](https://tools.ietf.org/html/rfc3046) (DHCP Relay Agent Information Option) so I don't expect it to work well with relayed requests anyway.

**Comment by rbclark** [comment]
In my testing I have found it works just fine with relayed requests as I've described (router in between). The only issue I have encountered is on the final DHCPACK. The current implementation does not respond since requests are coming from the router. 

Since this is already 99% of the way to working with DHCP relay would you consider removing this 1 check or adding an option so it works all the way? Is what I'm doing a hack?

**Comment by icb-** [comment]
@psychomario do you remember why we're checking the source address here? Looks like it was added initially in [148327](https://github.com/pypxe/PyPXE/blame/148327ee35d0ea5e1cbe77ae9656da44b32c1c98/server.py#L238) and [63e8ad](https://github.com/pypxe/PyPXE/blame/63e8ad26811d670bdceae38a6412adaf80b4cc45/server.py#L244).

[RFC2131 §4.1](https://tools.ietf.org/html/rfc2131#section-4.1) only seems to say to send from `0.0.0.0` before a client has *any* address, and doesn't say either way after it does.

> DHCP messages broadcast by a client prior to that client obtaining its IP address must have the source address field in the IP header set to 0.

A quick look through the `dnsmasq` source suggests it doesn't care about the source address of a `DHCPDISCOVER` either.

**Comment by psychomario** [comment]
Sorry for the delay.

It looks like a naive attempt to make proxydhcp work? Based on when it was added, and the rest of the code base at that time it's probably safe to say I was wrong and it should be removed.

**Comment by icb-** [comment]
@rbclark Can you try PR #173 and see if this fixes your problem?

**Comment by rbclark** [comment]
@icb- Yep this is nearly the exact fix I applied when testing to work around the issue. Thanks for the quick turnaround!
