### ISSUE TITLE
CAN use in windows?

### ISSUE THREAD

**Issue by m986883511** [pypxe/PyPXE#174]
I  want to use in windwos ,but does not effect.

set = {
    "ip":"10.90.116.248",
    'port':8088,
}
from pypxe import http
from pypxe import tftp
from pypxe import dhcp
dhcp.DHCPD()
tftp.TFTPD(**set)
http.HTTPD(**set)

while True:
    pass

**Comment by icb-** [comment]
Windows _may_ work, but as I don't have any Windows systems to test on, I can't say for sure if it does, or provide much help if it doesn't. At a minimum, getting the DHCP server to work is going to take quite a bit more than you've given there. Look at `pypxe.server` for what's needed, or the `pypxe` command that gets installed with the module.

**Comment by kongwei** [comment]
PyPXE  can used in windows.
Turn off firewall and retry.

**Comment by BiatuAutMiahn** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\****\AppData\Local\Programs\Python\Python311\Lib\site-packages\pypxe\dhcp.py", line 135, in __init__
    signal.signal(signal.SIGALRM, self.export_leases)
                  ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGALRM'. Did you mean: 'SIGABRT'?
```

**Comment by icb-** [comment]
Please put unrelated problems in new issues.

**Comment by BiatuAutMiahn** [comment]
THis is related to the issue, when I tried running dhcp.DHCPD() I got that error

**Comment by icb-** [comment]
[v1.8.4](https://github.com/pypxe/PyPXE/tree/v1.8.4) moves the signal handling to `pypxe.server`. Please update to that. Windows appears to not support `SIGALRM`, so you should be able to just [comment out registering that signal handler](https://github.com/pypxe/PyPXE/blob/v1.8.4/pypxe/server.py#L303). I don't have a Windows system to test on, so I can't help any further than that.
