### ISSUE TITLE
server.py fixes and updates

### ISSUE THREAD

**Issue by vbyrd** [pypxe/PyPXE#176]
I have created a pull request with some updates and cleanup for server.py. #175 

Fixes:
* HTTP Verbose logging was broken when called from server.py
* '--http' argument had an incorrect help description

Additions:
* '--http-server-ip' and supporting options. This is to match TFTP and DHCP servers
* Updated documentation and readme for the new option

**Comment by icb-** [comment]
Thanks for your contribution
