### ISSUE TITLE
Update description and documentation for Python 3 (Python 2.6 references)

### ISSUE THREAD

**Issue by jcea** [pypxe/PyPXE#178]
I wonder if 1.8 releases are Python 2 compatible. Let's suppose "no", Python 2.7 is legacy.

The description of the project says "Pure Python2 PXE (DHCP-(Proxy)/TFTP/HTTP/NBD) Server". Please, write "Python" or "Python 3".

Along the documentation there are references to Python 2.6. I suggest to update it to reflect compatibility with Python 3 and remove stale/outdated docs.

**Comment by icb-** [comment]
Thanks. I've removed references to Python 2, and tagged and pushed a new version with the recent fixes.

**Comment by jcea** [comment]
In the "about" column in https://github.com/pypxe/PyPXE (right column), you can still read "Pure Python2 PXE (DHCP-(Proxy)/TFTP/HTTP/NBD) Server"

**Comment by icb-** [comment]
Updated. Thanks.
