### ISSUE TITLE
PyPXE bails out when loading a JSON config - Followup

### ISSUE THREAD

**Issue by vbyrd** [pypxe/PyPXE#183]
This is a follow-up to my previous issue. 

My sincere apologies. My previous "fix" missed the point of the the conversion in the first place. we expect all JSON values to be Strings or Bools so we encode bytes into string. This blunder would only have been apparent if someone loaded a JSON config.

I have created PR-182 to fix and did detailed testing to make sure everything is kosher.

**Comment by icb-** [comment]
Merged. Thank you.
