### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by Sonny333Black** [pypxe/PyPXE#186]
please can you fix in tftp.py the line 131 
`response += str(self.blksize) + b'\x00'`
I think there is missing a part in the line.

before
`response += str(self.blksize) + b'\x00'`
after
`response += str(self.blksize).encode('ascii') + b'\x00'`

**Comment by icb-** [comment]
This should be fixed now that PR #187 is merged.
