### ISSUE TITLE
Release v1.8.3 and upload to pypi

### ISSUE THREAD

**Issue by tanty** [pypxe/PyPXE#194]
Commits 33dec45419d9ebe3c79fb756078c21528432dbbb , ce311ad095907f04c6806d0671909f4b8aac8570 and 89e75e23809f4e602bd98c236dbfc3e5a25d1f52 have landed after bumping to `v1.8.2` and are important fixes to make PyPXE usable.

Please, bump the version and upload the new one to pypi.

**Comment by icb-** [comment]
Done

**Comment by tanty** [comment]
Thanks a lot!
